name: Develop

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.0.4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
          cache: 'pnpm'
      - name: Install npm dependencies
        run: pnpm install
      - name: Run build task
        run: pnpm build
      - name: zip bundle file
        run: cd dist/chrome-mv3 && zip -r fisand-wxt.zip . && mv fisand-wxt.zip ../../
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: fisand-wxt
          path: fisand-wxt.zip